### ISSUE TITLE
Update repository file structure to CDSS standards

### ISSUE THREAD

**Issue by smalers** [jimbrannon/dwr_aug3_scripts#1]
The initial repository files need to be updated to be consistent with CDSS folder structure, add GPLv3+ license file, update README, etc.  Also use this as an example of a simple program development environment.

**Comment by maryhalstead** [comment]
Hi Steve,

After reviewing the github issue,  I assume this is how you initiate a task
in github and there is nothing for me to do right now but track.  Let me
know if you need me to do anything.  Take care,  Mary



*Mary Roberts HalsteadChief Modeling/DSS TeamP 303.866.3581 ext 8263 1313
Sherman Street, Room 821, Denver, CO 80203mary.halstead@state.co.us
<mary.halstead@state.co.us>  /  www.water.state.co.us
<http://www.water.state.co.us/>*

**Comment by smalers** [comment]
Correct...wanted to let you experience how it works.  I'm getting on the
plane to AZ and have my laptop to get AUG3 done.

**Comment by smalers** [comment]
I did a few things to bring the repository in line with OpenCDSS standards:

1. Added standard `.gitattributes` and `.gitignore` files.
2. Updated the `README.md` file to reflect changes.
3. Moved the source code into a `src` folder organized by language.
4. Added `build-util` folder with useful development scripts.
5. Copied the `makefile_linux` to `makefile` to more generically work with make command, and tested.
6. Added LICENSE.md file for license.
7. Updated the code to have the license/copyright notice at the top of *.for and *.inc files.
8. Added license/copyright notice for `--version` output.
9. Added more issues for things that need to be further resolved.

I'm closing this issue.  The other issues can be worked on separately.
