### ISSUE TITLE
Fix confusing version information

### ISSUE THREAD

**Issue by smalers** [jimbrannon/dwr_aug3_scripts#2]
The AUG3 version information is confusing and needs to be resolved.

1. The repository name includes `aug3` but source files use `aug4` in the names.  Is the number important or can it just be called `aug`?  GitHub tracks file versions so the filenames can be generic without the version.  It may be necessary to change the repository name to cdss-app-aug-fortran or something more explicit.
2. Source files have names that include `aug4` in the file name.  These could be changed to simply `aug` and rely on the software version for the version.
3. The version inside the file `aug4_db.for` contains a line ` data ver        /' 0.81'/`, which apparently indicates the software version.  Perhaps this should be set to 4.81 or 4.0.81 indicating that the program major version is 4, with a minor version?  For CDSS versions are typically Major.Minor.BugFix where the major version indicates a substantial design change, minor is a new feature, and bug fix is no new feature but is a fix to previously released features.
4. A number of documents and scripts are now in place that use the confusing version information and would need to be corrected.

I don't know how to clean this up without input from the State.

**Comment by maryhalstead** [comment]
AUG3 is the title of the Project and consists of four applications, 18 MODFLOW models, pre/post processors, and an excel interface.  The AUG3 Project is stored and managed on a CDWR server.  To assist in running the groundwater models, a processing program entitled AUG3.BAS, was developed at the same time as the original Denver Basin Groundwater Model. This program was designed to assist users in preparing model input files (pre-processing) and in processing model results on the DOS window (post-processing).  For creating the EXCEL interface, AUG4.BAS was created from AUG3.BAS to effectively operate AUG3 by changing certain code and removing some of options provided by AUG3.BAS.
Both AUG3.BAS and AUG4.BAS were written in GW-BASIC, an older computer language that cannot be used with a 64-bit version of Microsoft Windows. The decision was made to rewrite AUG4.BAS in FORTRAN. The new FORTRAN pre-processing program is now named AUG4.for and is compiled as AUG4.exe.  Accordingly, the EXCEL interface was modified to incorporate the changes in AUG4.exe.   Additionally, a GW-BASIC post-processing program, DRY.BAS, was also rewritten in FORTRAN (dry.exe) to report dry cells in the output file.
