### ISSUE TITLE
Unclear what files should be packaged for release

### ISSUE THREAD

**Issue by smalers** [jimbrannon/dwr_aug3_scripts#5]
It is not clear what should be packaged for release of the software?  `aug4.exe`, `aug4_db.exe`, and `dry.exe`?  Which Excel file?  Is there a production Excel file that is not a test version?  Once clarified, a zip file can be created for distribution of the files.

**Comment by maryhalstead** [comment]
This repository is only for archiving the 4 FORTRAN programs used by the AUG3 Project (aug4, aug4_db, dry, and GS3DRIVE.  The project consists of over 400 files (Fortran, GIS, GMS, data, excel, word etc.) and is stored on a CDWR server folder.  A task to look at moving the entire AUG3 Project to GitHub has been added to the project management document for consideration in the future.  Currently, the AUG3 Project Manager (Mary Halstead) coordinates and packages new releases of the Project.
