### ISSUE TITLE
Need user documentation

### ISSUE THREAD

**Issue by smalers** [jimbrannon/dwr_aug3_scripts#6]
The documentation provided by Mary is pretty minimal and does not really describe how to use the software.  The documentation was also provided as PDF, whereas the repository should hold the original Word document if available.   Perhaps the documentation could use the test files to explain how the software works.

**Comment by maryhalstead** [comment]
There is no documentation for the GWBASIC & FORTRAN programs.  These programs were written around 1985 and all information is contained in comments in the code.  The consultant who rewrote the AUG4.bas and DRY.bas into FORTRAN was hired on a minimal budget with no money for documentation.  Significant documentation on the AUG3 Project is provided in the releases and even more documentation is provided on the CDWR project server.
