### ISSUE TITLE
Need test documentation

### ISSUE THREAD

**Issue by smalers** [jimbrannon/dwr_aug3_scripts#7]
The test needs to be documented.  Without spending time on it, I don't know what I need to do to run the test, and how does one know that the software passed the test?  Basic documentation of the test is needed to help software developers.

**Comment by maryhalstead** [comment]
Testing of the code was done through the EXCEL interface and was documented in the project folder outside of GitHub.  A task to upgrade the testing process and incorporate the testing using the GitHub site will be added to the project management documentation for future consideration.
